name: Playwright API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd playwright-api-101
          npm ci

      - name: Run Playwright tests with Allure reporter
        run: |
          cd playwright-api-101
          npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report
        run: |
          cd playwright-api-101
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: playwright-api-101/allure-report 